swagger: '2.0'
info:
  title: Story Upload API
  version: 1.0.0
basePath: /api
schemes:
  - http
  - https
tags:
  - name: Auth
    description: Authentication operations
  - name: Stories
    description: Story operations
securityDefinitions:
  BearerAuth:
    type: apiKey
    in: header
    name: Authorization
paths:
  /auth/register:
    post:
      summary: Register a new user
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        '200':
          description: User successfully registered
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /auth/login:
    post:
      summary: Login user
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        '200':
          description: User successfully logged in. Include a Bearer token in the response.
        '401':
          description: Unauthorized. Invalid credentials.
        '500':
          description: Internal Server Error

  /stories:
    get:
      summary: Get all stories
      responses:
        '200':
          description: List of stories retrieved successfully
        '401':
          description: Unauthorized access (if authentication is required)
        '500':
          description: Internal Server Error

  /stories/upload:
    post:
      summary: Upload a new story (only for admin user)
      security:
        - BearerAuth: []
      parameters:
        - name: title
          in: formData
          type: string
          required: true
          description: Title of the story
        - name: content
          in: formData
          type: string
          required: true
          description: Content of the story
      responses:
        '200':
          description: Story successfully uploaded
        '401':
          description: Only admin users can upload stories
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /stories/like/{storyId}:
    post:
      summary: Like a story
      security:
        - BearerAuth: []
      parameters:
        - name: storyId
          in: path
          type: string
          required: true
          description: ID of the story to like
      responses:
        '200':
          description: Story liked successfully
        '401':
          description: Invalid token or user not authorized
        '404':
          description: Story not found
        '500':
          description: Internal Server Error

  /stories/comment/{storyId}:
    post:
      summary: Comment on a story
      security:
        - BearerAuth: []
      parameters:
        - name: storyId
          in: path
          type: string
          required: true
          description: ID of the story to comment on
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
            description: Comment text
      responses:
        '200':
          description: Comment added successfully
        '401':
          description: Invalid token or user not authorized
        '404':
          description: Story not found
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
